//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiGames.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MultiGames_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MultiGames_Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiGames.Domain.Resources.MultiGames.Resource", typeof(MultiGames_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número do telefone celular não pode ser vazio.
        /// </summary>
        public static string CelPhoneEmpty {
            get {
                return ResourceManager.GetString("CelPhoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número do telefone celular invalido.
        /// </summary>
        public static string CelPhoneInvalid {
            get {
                return ResourceManager.GetString("CelPhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número do telefone celular não pode ser nulo.
        /// </summary>
        public static string CelPhoneNull {
            get {
                return ResourceManager.GetString("CelPhoneNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome da cidade não pode ser vazio.
        /// </summary>
        public static string CityEmpty {
            get {
                return ResourceManager.GetString("CityEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome da cidade não pode ser nulo.
        /// </summary>
        public static string CityNull {
            get {
                return ResourceManager.GetString("CityNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do país não pode ser vazio.
        /// </summary>
        public static string CountryEmpty {
            get {
                return ResourceManager.GetString("CountryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do país não pode ser nulo.
        /// </summary>
        public static string CountryNull {
            get {
                return ResourceManager.GetString("CountryNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF com digitação inválida.
        /// </summary>
        public static string CpfDigtInvalid {
            get {
                return ResourceManager.GetString("CpfDigtInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CPF não pode ser vazio.
        /// </summary>
        public static string CpfEmpty {
            get {
                return ResourceManager.GetString("CpfEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CPF não pode ser nulo.
        /// </summary>
        public static string CpfNull {
            get {
                return ResourceManager.GetString("CpfNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF com numeração inválida.
        /// </summary>
        public static string CpfNumberInvalid {
            get {
                return ResourceManager.GetString("CpfNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Email não pode ser vazio.
        /// </summary>
        public static string EmailEmpty {
            get {
                return ResourceManager.GetString("EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço de Email é inválido.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Email não pode ser nulo.
        /// </summary>
        public static string EmailNull {
            get {
                return ResourceManager.GetString("EmailNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código postal não pode ser vazio.
        /// </summary>
        public static string PostalCodeEmpty {
            get {
                return ResourceManager.GetString("PostalCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código postal não pode ser nulo.
        /// </summary>
        public static string PostalCodeNull {
            get {
                return ResourceManager.GetString("PostalCodeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do estado não pode ser vazio.
        /// </summary>
        public static string StateEmpty {
            get {
                return ResourceManager.GetString("StateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do estado não pode ser nulo.
        /// </summary>
        public static string StateNull {
            get {
                return ResourceManager.GetString("StateNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome da rua não pode ser vazio.
        /// </summary>
        public static string StreetEmpty {
            get {
                return ResourceManager.GetString("StreetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome da rua não pode ser nulo.
        /// </summary>
        public static string StreetNull {
            get {
                return ResourceManager.GetString("StreetNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número não pode ser vazio.
        /// </summary>
        public static string StreetNumberEmpty {
            get {
                return ResourceManager.GetString("StreetNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número não pode ser nullo.
        /// </summary>
        public static string StreetNumberNull {
            get {
                return ResourceManager.GetString("StreetNumberNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número do telefone convencional não pode ser vazio.
        /// </summary>
        public static string TelPhoneEmpty {
            get {
                return ResourceManager.GetString("TelPhoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número do telefone convencional inválido.
        /// </summary>
        public static string TelPhoneInvalid {
            get {
                return ResourceManager.GetString("TelPhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número do telefone convencional não pode ser nulo.
        /// </summary>
        public static string TelPhoneNull {
            get {
                return ResourceManager.GetString("TelPhoneNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do usuário não pode ser vazio.
        /// </summary>
        public static string UserNameEmpty {
            get {
                return ResourceManager.GetString("UserNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do usuário não pode ser nulo.
        /// </summary>
        public static string UserNameNull {
            get {
                return ResourceManager.GetString("UserNameNull", resourceCulture);
            }
        }
    }
}
